// Shared constants for Lambda functions

export const TIMEOUTS = {
  JWT_EXPIRATION: 3600, // 1 hour
  API_REQUEST: 30000, // 30 seconds
  SERVER_STARTUP: 300000, // 5 minutes
  MONITOR_INTERVAL: 120000, // 2 minutes
  PARAMETER_CACHE_TTL: 300000 // 5 minutes (for parameter-cache.ts)
} as const;

export const RETRY_LIMITS = {
  API_READINESS_CHECKS: 30,
  AWS_SERVICE_CALLS: 3
} as const;

export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const ERROR_CODES = {
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVER_NOT_RUNNING: 'SERVER_NOT_RUNNING',
  SERVER_START_FAILED: 'SERVER_START_FAILED',
  SERVER_STOP_FAILED: 'SERVER_STOP_FAILED',
  API_TOKEN_ERROR: 'API_TOKEN_ERROR',
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',
  PARAMETER_NOT_FOUND: 'PARAMETER_NOT_FOUND',
  PARAMETER_ACCESS_DENIED: 'PARAMETER_ACCESS_DENIED',
  NOT_FOUND: 'NOT_FOUND'
} as const;