#!/bin/bash

# Post-deployment script for Satisfactory On-Demand Server
# This script configures secrets and environment variables after CloudFormation deployment

set -e  # Exit on any error

# Configuration
STACK_NAME="satisfactory-server"
ADMIN_PASSWORD_SECRET="satisfactory-admin-password"
JWT_SECRET_SECRET="satisfactory-jwt-secret"
ENV_FILE="admin-panel/.env.local"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Satisfactory On-Demand Server Post-Deployment Configuration ===${NC}"
echo

# Function to generate secure random password
generate_password() {
    local length=$1
    # Generate extra characters to ensure we have enough after filtering
    local extra_length=$((length + 8))
    openssl rand -base64 $extra_length | tr -d "=+/\n" | cut -c1-${length}
}

# Function to check if secret exists and has a value
check_secret_exists() {
    local secret_name=$1
    local secret_value
    
    secret_value=$(aws secretsmanager get-secret-value --secret-id "$secret_name" --query 'SecretString' --output text 2>/dev/null || echo "")
    
    if [[ -n "$secret_value" && "$secret_value" != "placeholder" ]]; then
        return 0  # Secret exists and has a real value
    else
        return 1  # Secret doesn't exist or has placeholder value
    fi
}

# Function to update secret value
update_secret() {
    local secret_name=$1
    local secret_value=$2
    
    echo -e "Updating secret: ${YELLOW}$secret_name${NC}"
    aws secretsmanager put-secret-value \
        --secret-id "$secret_name" \
        --secret-string "$secret_value" \
        --output text > /dev/null
    
    if [[ $? -eq 0 ]]; then
        echo -e "${GREEN}✓${NC} Secret updated successfully"
    else
        echo -e "${RED}✗${NC} Failed to update secret"
        exit 1
    fi
}

# Check AWS CLI is configured
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo -e "${RED}Error: AWS CLI is not configured or credentials are invalid${NC}"
    echo "Please run 'aws configure' to set up your credentials"
    exit 1
fi

echo -e "${BLUE}Step 1: Checking and configuring secrets${NC}"
echo

# Check and generate admin password
if check_secret_exists "$ADMIN_PASSWORD_SECRET"; then
    echo -e "${GREEN}✓${NC} Admin password already exists"
    ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id "$ADMIN_PASSWORD_SECRET" --query 'SecretString' --output text)
else
    echo -e "${YELLOW}!${NC} Admin password not found, generating new password..."
    ADMIN_PASSWORD=$(generate_password 32)
    update_secret "$ADMIN_PASSWORD_SECRET" "$ADMIN_PASSWORD"
fi

# Check and generate JWT secret
if check_secret_exists "$JWT_SECRET_SECRET"; then
    echo -e "${GREEN}✓${NC} JWT secret already exists"
else
    echo -e "${YELLOW}!${NC} JWT secret not found, generating new secret..."
    JWT_SECRET=$(generate_password 64)
    update_secret "$JWT_SECRET_SECRET" "$JWT_SECRET"
fi

echo
echo -e "${BLUE}Step 2: Retrieving API Gateway URL${NC}"
echo

# Get API Gateway URL from CloudFormation outputs
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
    --output text 2>/dev/null)

if [[ -z "$API_URL" || "$API_URL" == "None" ]]; then
    echo -e "${RED}Error: Could not retrieve API Gateway URL from CloudFormation stack${NC}"
    echo "Make sure the CloudFormation stack '$STACK_NAME' exists and has been deployed successfully"
    exit 1
fi

echo -e "${GREEN}✓${NC} API Gateway URL: $API_URL"

echo
echo -e "${BLUE}Step 3: Configuring Admin Panel environment${NC}"
echo

# Create admin-panel directory if it doesn't exist
mkdir -p admin-panel

# Create or update .env.local file
cat > "$ENV_FILE" << EOF
# Satisfactory On-Demand Server Configuration
# Generated by post-deploy.sh on $(date)

# API Gateway URL from CloudFormation
VITE_API_URL=$API_URL
EOF

echo -e "${GREEN}✓${NC} Environment file created: $ENV_FILE"

echo
echo -e "${BLUE}Step 4: Configuration Summary${NC}"
echo

echo -e "${GREEN}✓${NC} Post-deployment configuration completed successfully!"
echo
echo -e "${YELLOW}Important Information:${NC}"
echo -e "  Admin Password: ${GREEN}$ADMIN_PASSWORD${NC}"
echo -e "  API URL: ${BLUE}$API_URL${NC}"
echo -e "  Environment File: ${BLUE}$ENV_FILE${NC}"
echo
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Build the Admin Panel:"
echo "   cd admin-panel && npm install && npm run build"
echo
echo "2. Upload Admin Panel to S3 (get bucket name from CloudFormation outputs):"
echo "   aws s3 sync admin-panel/dist s3://\$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==\`S3BucketName\`].OutputValue' --output text)/"
echo
echo "3. Access the Admin Panel using the CloudFront URL or S3 website URL"
echo "4. Login with the admin password shown above"
echo
echo -e "${GREEN}Setup complete!${NC}"